#!/usr/bin/env node
/**
 * Assemble the single self-contained page.
 *
 *   fantasy-football/src/*  ->  fantasy-football.html
 *
 * Everything (three.js, the player pool, styles, app code) is inlined so the
 * file works from disk, from GitHub Pages, or from anywhere else with no
 * build step and no network dependency beyond optional player headshots.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const src = (f) => fs.readFileSync(path.join(here, 'src', f), 'utf8');
const OUT = path.join(here, '..', 'fantasy-football.html');

const css = src('app.css');
const three = src('three.min.js');
const pool = src('pool.json');
const app = src('app.js');

// three-scenes.js is authored as an ES module for editing; the page inlines it
// inside an IIFE, so drop the export keywords.
const scenes = src('three-scenes.js').replace(/^export\s+/gm, '');

let html = src('shell.html');
const put = (token, value) => {
  const marker = `/*__${token}__*/`;
  if (!html.includes(marker)) throw new Error(`shell.html is missing ${marker}`);
  // Use a function replacer so $& / $1 in the payload are not interpreted.
  html = html.replace(marker, () => value);
};

put('CSS', css);
put('THREE', three);
put('POOL', pool);
put('SCENES', scenes);
put('APP', app);

const banner = `<!doctype html>
<!--
  Gridiron — fantasy football league (self-contained)

  Player data: nflverse open data (github.com/nflverse) — ${JSON.parse(pool).players.length} players,
  ranked by ${JSON.parse(pool).basis} per-game production above positional replacement.

  Runs standalone against CPU managers with no server. To play a shared league
  with live NFL scoring, deploy fantasy-football/worker (Cloudflare Workers +
  Durable Objects) and paste its URL into the "Shared league" tab.

  Generated by fantasy-football/build.mjs — edit files in fantasy-football/src
  and re-run \`node fantasy-football/build.mjs\`, not this file.
-->
`;

fs.writeFileSync(OUT, banner + html);

const kb = (n) => (n / 1024).toFixed(1) + 'KB';
console.log(`wrote ${path.relative(process.cwd(), OUT)}  ${kb(fs.statSync(OUT).size)}`);
console.log(`  three.js ${kb(three.length)} · pool ${kb(pool.length)} · app ${kb(app.length)} · scenes ${kb(scenes.length)} · css ${kb(css.length)}`);
